name = "copenhagenmarathon"  # Name of your Worker

# Specify the entry-point script
main = "worker.js"
compatibility_date = "2024-10-29"  # Set the compatibility date

kv_namespaces = [
  { binding = "copenhagenMarathon", id = "f4dc5a515ccf4e919761c04edf96eab0" }
]

send_email = [
    {name = "SEB"},
]

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["*/1 * * * *"]

[vars]
PUSHOVER_TOKEN
PUSHOVER_USER

 